"""
Funções utilitárias e mapeamentos para o projeto juscraper.
Inclui: limpeza e formatação de CNJ, dicionários de mapeamento de tribunais.
"""

def clean_cnj(numero: str) -> str:
    """Formata o número do processo para o padrão esperado."""
    return numero.replace(".", "").replace("-", "")

def format_cnj(numero: str) -> str:
    """Formata o número do processo para o padrão brasileiro."""
    p = split_cnj(numero)
    return f"{p['num']}-{p['dv']}.{p['ano']}.{p['justica']}.{p['tribunal']}.{p['orgao']}"

def split_cnj(numero: str) -> str:
    """Formata o número do processo para o padrão brasileiro."""
    dicionario = {
      "num": numero[:7],
      "dv": numero[7:9],
      "ano": numero[9:13],
      "justica": numero[13:14],
      "tribunal": numero[14:16],
      "orgao": numero[16:]
    }
    return dicionario

# Mapeamento completo de (id_justica, id_tribunal) para alias da API pública do Datajud
ID_JUSTICA_TRIBUNAL_TO_ALIAS = {
    ("1", "00"): "api_publica_stf",
    ("2", "00"): "api_publica_cnj",
    ("3", "00"): "api_publica_stj",
    ("4", "90"): "api_publica_cjf",
    ("5", "00"): "api_publica_tst",
    ("5", "90"): "api_publica_csjt",
    ("6", "00"): "api_publica_tse",
    ("7", "00"): "api_publica_stm",
    ("4", "01"): "api_publica_trf1",
    ("4", "02"): "api_publica_trf2",
    ("4", "03"): "api_publica_trf3",
    ("4", "04"): "api_publica_trf4",
    ("4", "05"): "api_publica_trf5",
    ("5", "01"): "api_publica_trt01",
    ("5", "02"): "api_publica_trt02",
    ("5", "03"): "api_publica_trt03",
    ("5", "04"): "api_publica_trt04",
    ("5", "05"): "api_publica_trt05",
    ("5", "06"): "api_publica_trt06",
    ("5", "07"): "api_publica_trt07",
    ("5", "08"): "api_publica_trt08",
    ("5", "09"): "api_publica_trt09",
    ("5", "10"): "api_publica_trt10",
    ("5", "11"): "api_publica_trt11",
    ("5", "12"): "api_publica_trt12",
    ("5", "13"): "api_publica_trt13",
    ("5", "14"): "api_publica_trt14",
    ("5", "15"): "api_publica_trt15",
    ("5", "16"): "api_publica_trt16",
    ("5", "17"): "api_publica_trt17",
    ("5", "18"): "api_publica_trt18",
    ("5", "19"): "api_publica_trt19",
    ("5", "20"): "api_publica_trt20",
    ("5", "21"): "api_publica_trt21",
    ("5", "22"): "api_publica_trt22",
    ("5", "23"): "api_publica_trt23",
    ("5", "24"): "api_publica_trt24",
    ("6", "01"): "api_publica_tre-ac",
    ("6", "02"): "api_publica_tre-al",
    ("6", "03"): "api_publica_tre-ap",
    ("6", "04"): "api_publica_tre-am",
    ("6", "05"): "api_publica_tre-ba",
    ("6", "06"): "api_publica_tre-ce",
    ("6", "07"): "api_publica_tre-df",
    ("6", "08"): "api_publica_tre-es",
    ("6", "09"): "api_publica_tre-go",
    ("6", "10"): "api_publica_tre-ma",
    ("6", "11"): "api_publica_tre-mt",
    ("6", "12"): "api_publica_tre-ms",
    ("6", "13"): "api_publica_tre-mg",
    ("6", "14"): "api_publica_tre-pa",
    ("6", "15"): "api_publica_tre-pb",
    ("6", "16"): "api_publica_tre-pr",
    ("6", "17"): "api_publica_tre-pe",
    ("6", "18"): "api_publica_tre-pi",
    ("6", "19"): "api_publica_tre-rj",
    ("6", "20"): "api_publica_tre-rn",
    ("6", "21"): "api_publica_tre-rs",
    ("6", "22"): "api_publica_tre-ro",
    ("6", "23"): "api_publica_tre-rr",
    ("6", "24"): "api_publica_tre-sc",
    ("6", "25"): "api_publica_tre-se",
    ("6", "26"): "api_publica_tre-sp",
    ("6", "27"): "api_publica_tre-to",
    ("7", "01"): "api_publica_cjm01",
    ("7", "02"): "api_publica_cjm02",
    ("7", "03"): "api_publica_cjm03",
    ("7", "04"): "api_publica_cjm04",
    ("7", "05"): "api_publica_cjm05",
    ("7", "06"): "api_publica_cjm06",
    ("7", "07"): "api_publica_cjm07",
    ("7", "08"): "api_publica_cjm08",
    ("7", "09"): "api_publica_cjm09",
    ("7", "10"): "api_publica_cjm10",
    ("7", "11"): "api_publica_cjm11",
    ("7", "12"): "api_publica_cjm12",
    ("8", "01"): "api_publica_tjac",
    ("8", "02"): "api_publica_tjal",
    ("8", "03"): "api_publica_tjap",
    ("8", "04"): "api_publica_tjam",
    ("8", "05"): "api_publica_tjba",
    ("8", "06"): "api_publica_tjce",
    ("8", "07"): "api_publica_tjdft",
    ("8", "08"): "api_publica_tjes",
    ("8", "09"): "api_publica_tjgo",
    ("8", "10"): "api_publica_tjma",
    ("8", "11"): "api_publica_tjmt",
    ("8", "12"): "api_publica_tjms",
    ("8", "13"): "api_publica_tjmg",
    ("8", "14"): "api_publica_tjpa",
    ("8", "15"): "api_publica_tjpb",
    ("8", "16"): "api_publica_tjpr",
    ("8", "17"): "api_publica_tjpe",
    ("8", "18"): "api_publica_tjpi",
    ("8", "19"): "api_publica_tjrj",
    ("8", "20"): "api_publica_tjrn",
    ("8", "21"): "api_publica_tjrs",
    ("8", "22"): "api_publica_tjro",
    ("8", "23"): "api_publica_tjrr",
    ("8", "24"): "api_publica_tjsc",
    ("8", "25"): "api_publica_tjse",
    ("8", "26"): "api_publica_tjsp",
    ("8", "27"): "api_publica_tjto",
    ("9", "13"): "api_publica_tjmmg",
    ("9", "21"): "api_publica_tjmrs",
    ("9", "26"): "api_publica_tjmsp",
}

# Mapeamento de siglas de tribunais para aliases da API pública do Datajud
TRIBUNAL_ALIASES = {
    # Tribunais Superiores
    "STF": "api_publica_stf",
    "CNJ": "api_publica_cnj",
    "STJ": "api_publica_stj",
    "CJF": "api_publica_cjf",
    "TST": "api_publica_tst",
    "CSJT": "api_publica_csjt",
    "TSE": "api_publica_tse",
    "STM": "api_publica_stm",

    # TRFs
    "TRF1": "api_publica_trf1",
    "TRF2": "api_publica_trf2",
    "TRF3": "api_publica_trf3",
    "TRF4": "api_publica_trf4",
    "TRF5": "api_publica_trf5",

    # TJs (principais)
    "TJAC": "api_publica_tjac",
    "TJAL": "api_publica_tjal",
    "TJAP": "api_publica_tjap",
    "TJAM": "api_publica_tjam",
    "TJBA": "api_publica_tjba",
    "TJCE": "api_publica_tjce",
    "TJDFT": "api_publica_tjdft",
    "TJES": "api_publica_tjes",
    "TJGO": "api_publica_tjgo",
    "TJMA": "api_publica_tjma",
    "TJMT": "api_publica_tjmt",
    "TJMS": "api_publica_tjms",
    "TJMG": "api_publica_tjmg",
    "TJPA": "api_publica_tjpa",
    "TJPB": "api_publica_tjpb",
    "TJPR": "api_publica_tjpr",
    "TJPE": "api_publica_tjpe",
    "TJPI": "api_publica_tjpi",
    "TJRJ": "api_publica_tjrj",
    "TJRN": "api_publica_tjrn",
    "TJRS": "api_publica_tjrs",
    "TJRO": "api_publica_tjro",
    "TJRR": "api_publica_tjrr",
    "TJSC": "api_publica_tjsc",
    "TJSE": "api_publica_tjse",
    "TJSP": "api_publica_tjsp",
    "TJTO": "api_publica_tjto",

    # TREs (principais)
    "TRE-AC": "api_publica_tre-ac",
    "TRE-AL": "api_publica_tre-al",
    "TRE-AP": "api_publica_tre-ap",
    "TRE-AM": "api_publica_tre-am",
    "TRE-BA": "api_publica_tre-ba",
    "TRE-CE": "api_publica_tre-ce",
    "TRE-DF": "api_publica_tre-df",
    "TRE-ES": "api_publica_tre-es",
    "TRE-GO": "api_publica_tre-go",
    "TRE-MA": "api_publica_tre-ma",
    "TRE-MT": "api_publica_tre-mt",
    "TRE-MS": "api_publica_tre-ms",
    "TRE-MG": "api_publica_tre-mg",
    "TRE-PA": "api_publica_tre-pa",
    "TRE-PB": "api_publica_tre-pb",
    "TRE-PR": "api_publica_tre-pr",
    "TRE-PE": "api_publica_tre-pe",
    "TRE-PI": "api_publica_tre-pi",
    "TRE-RJ": "api_publica_tre-rj",
    "TRE-RN": "api_publica_tre-rn",
    "TRE-RO": "api_publica_tre-ro",
    "TRE-RR": "api_publica_tre-rr",
    "TRE-RS": "api_publica_tre-rs",
    "TRE-SC": "api_publica_tre-sc",
    "TRE-SE": "api_publica_tre-se",
    "TRE-SP": "api_publica_tre-sp",
    "TRE-TO": "api_publica_tre-to",
}

# Mapeamento completo de (id_justica, id_tribunal) para alias da API pública do Datajud
ID_JUSTICA_TRIBUNAL_TO_ALIAS = {
    ("1", "00"): "api_publica_stf",
    ("2", "00"): "api_publica_cnj",
    ("3", "00"): "api_publica_stj",
    ("4", "90"): "api_publica_cjf",
    ("5", "00"): "api_publica_tst",
    ("5", "90"): "api_publica_csjt",
    ("6", "00"): "api_publica_tse",
    ("7", "00"): "api_publica_stm",
    ("4", "01"): "api_publica_trf1",
    ("4", "02"): "api_publica_trf2",
    ("4", "03"): "api_publica_trf3",
    ("4", "04"): "api_publica_trf4",
    ("4", "05"): "api_publica_trf5",
    ("5", "01"): "api_publica_trt01",
    ("5", "02"): "api_publica_trt02",
    ("5", "03"): "api_publica_trt03",
    ("5", "04"): "api_publica_trt04",
    ("5", "05"): "api_publica_trt05",
    ("5", "06"): "api_publica_trt06",
    ("5", "07"): "api_publica_trt07",
    ("5", "08"): "api_publica_trt08",
    ("5", "09"): "api_publica_trt09",
    ("5", "10"): "api_publica_trt10",
    ("5", "11"): "api_publica_trt11",
    ("5", "12"): "api_publica_trt12",
    ("5", "13"): "api_publica_trt13",
    ("5", "14"): "api_publica_trt14",
    ("5", "15"): "api_publica_trt15",
    ("5", "16"): "api_publica_trt16",
    ("5", "17"): "api_publica_trt17",
    ("5", "18"): "api_publica_trt18",
    ("5", "19"): "api_publica_trt19",
    ("5", "20"): "api_publica_trt20",
    ("5", "21"): "api_publica_trt21",
    ("5", "22"): "api_publica_trt22",
    ("5", "23"): "api_publica_trt23",
    ("5", "24"): "api_publica_trt24",
    ("6", "01"): "api_publica_tre-ac",
    ("6", "02"): "api_publica_tre-al",
    ("6", "03"): "api_publica_tre-ap",
    ("6", "04"): "api_publica_tre-am",
    ("6", "05"): "api_publica_tre-ba",
    ("6", "06"): "api_publica_tre-ce",
    ("6", "07"): "api_publica_tre-df",
    ("6", "08"): "api_publica_tre-es",
    ("6", "09"): "api_publica_tre-go",
    ("6", "10"): "api_publica_tre-ma",
    ("6", "11"): "api_publica_tre-mt",
    ("6", "12"): "api_publica_tre-ms",
    ("6", "13"): "api_publica_tre-mg",
    ("6", "14"): "api_publica_tre-pa",
    ("6", "15"): "api_publica_tre-pb",
    ("6", "16"): "api_publica_tre-pr",
    ("6", "17"): "api_publica_tre-pe",
    ("6", "18"): "api_publica_tre-pi",
    ("6", "19"): "api_publica_tre-rj",
    ("6", "20"): "api_publica_tre-rn",
    ("6", "21"): "api_publica_tre-rs",
    ("6", "22"): "api_publica_tre-ro",
    ("6", "23"): "api_publica_tre-rr",
    ("6", "24"): "api_publica_tre-sc",
    ("6", "25"): "api_publica_tre-se",
    ("6", "26"): "api_publica_tre-sp",
    ("6", "27"): "api_publica_tre-to",
    ("7", "01"): "api_publica_cjm01",
    ("7", "02"): "api_publica_cjm02",
    ("7", "03"): "api_publica_cjm03",
    ("7", "04"): "api_publica_cjm04",
    ("7", "05"): "api_publica_cjm05",
    ("7", "06"): "api_publica_cjm06",
    ("7", "07"): "api_publica_cjm07",
    ("7", "08"): "api_publica_cjm08",
    ("7", "09"): "api_publica_cjm09",
    ("7", "10"): "api_publica_cjm10",
    ("7", "11"): "api_publica_cjm11",
    ("7", "12"): "api_publica_cjm12",
    ("8", "01"): "api_publica_tjac",
    ("8", "02"): "api_publica_tjal",
    ("8", "03"): "api_publica_tjap",
    ("8", "04"): "api_publica_tjam",
    ("8", "05"): "api_publica_tjba",
    ("8", "06"): "api_publica_tjce",
    ("8", "07"): "api_publica_tjdft",
    ("8", "08"): "api_publica_tjes",
    ("8", "09"): "api_publica_tjgo",
    ("8", "10"): "api_publica_tjma",
    ("8", "11"): "api_publica_tjmt",
    ("8", "12"): "api_publica_tjms",
    ("8", "13"): "api_publica_tjmg",
    ("8", "14"): "api_publica_tjpa",
    ("8", "15"): "api_publica_tjpb",
    ("8", "16"): "api_publica_tjpr",
    ("8", "17"): "api_publica_tjpe",
    ("8", "18"): "api_publica_tjpi",
    ("8", "19"): "api_publica_tjrj",
    ("8", "20"): "api_publica_tjrn",
    ("8", "21"): "api_publica_tjrs",
    ("8", "22"): "api_publica_tjro",
    ("8", "23"): "api_publica_tjrr",
    ("8", "24"): "api_publica_tjsc",
    ("8", "25"): "api_publica_tjse",
    ("8", "26"): "api_publica_tjsp",
    ("8", "27"): "api_publica_tjto",
    ("9", "13"): "api_publica_tjmmg",
    ("9", "21"): "api_publica_tjmrs",
    ("9", "26"): "api_publica_tjmsp",
}
